### ISSUE TITLE
deprecated state.get_attr() doesn't work in 1.0.0

### ISSUE THREAD

**Issue by tal** [custom-components/pyscript#92]
When I updated to the latest version my code like this `attrs = state.getattr(entity_id)` is no longer returning a dictionary that can respond to the `get()` method.

After a none check I'd previously use the following code:

```
current_brightness = attrs.get("brightness", 0)
```

Now i have to do

```
starting_brightness = 0
if "brightness" in attrs:
  starting_brightness = attrs["brightness"]
```

**Comment by craigbarratt** [comment]
If you `print(attrs)` what output do you get?

This example works for me:
```python
attrs = state.getattr("sun.sun")
print(f"attrs={attrs}")
print(f"attrs.get('next_dawn')={attrs.get('next_dawn')}")
```
produces the output:
```
attrs={'next_dawn': '2020-11-24T14:32:08+00:00', 'next_dusk': '2020-11-24T01:23:52+00:00', 'next_midnight': '2020-11-24T07:57:33+00:00', 'next_noon': '2020-11-23T19:57:01+00:00', 'next_rising': '2020-11-24T14:59:29+00:00', 'next_setting': '2020-11-24T00:56:33+00:00', 'elevation': 32.83, 'azimuth': 175.47, 'rising': True, 'friendly_name': 'Sun'}
attrs.get('next_dawn')=2020-11-24T14:32:08+00:00
```

**Comment by tal** [comment]
So I'm getting an interesting heizenbug.

I run the code as listed above and get this error.
```
      starting_brightness = attrs.get("brightness", 0)
                            ^
AttributeError: 'coroutine' object has no attribute 'get'
```

When I add the logging you describe it works fine...

**Comment by craigbarratt** [comment]
The plot thickens...

Can you include the exact code where `attrs` is set?  Somehow it got set to a coroutine; not sure how that would happen.

Hopefully there is some way to create the issue in a small, self-contained script.

**Comment by tal** [comment]
This is what I used to test the issue

```python
@service
def test_attrs():
  log.info("1")
  entity_id = 'light.kids_bedroom_main_lights'
  attrs = state.get_attr(entity_id)
  log.error(f"attrs={attrs}")
  log.error(f"attrs.get('brightness')={attrs.get('brightness', 0)}")
```

I alternated it between `get_attr` and `getattr`.

**Comment by dlashua** [comment]
If you are running the released pyscript 1.0.0 you will need to use `state.getattr()` instead of `state.get_attr()`. If you pull the current "master", either of these should work, though get_attr is deprecated.  I've tested your exact code (changing only the entity_id line to a valid ID in my system) and it works fine on the latest "master".

**Comment by tal** [comment]
The problem I had was in my migrating from `get_attr` -> `getattr`. It's
probably an edge case with caching that isn't worth fixing. But at first I
didn't realize it was caching.

**Comment by craigbarratt** [comment]
Yes - there is a bug in 1.0.0 with the deprecated `get_attr()` function.  It will cause the co-routine to get returned, instead of calling it to get the `dict`.  @dlashua fixed it in #88.

It seemed minor enough so I didn't release a 1.0.1 to fix it.  As you discovered, the fix is to either run the master version, or change to using `getattr()`.

**Comment by tal** [comment]
Ah, makes perfect sense.
