### ISSUE TITLE
AttributeError: module 'homeassistant.helpers.template' has no attribute 'now'

### ISSUE THREAD

**Issue by phsdv** [custom-components/pyscript#783]
Since update to 2025.12 I get error: AttributeError: module 'homeassistant.helpers.template' has no attribute 'now'

The error happens in:
```
from homeassistant.helpers import template

# ===========================================================================
# original code
# ===========================================================================
def circadian_setting():
    """ returns new brightness and color temperature """
    now = template.now(hass).hour * 100 + template.now(hass).minute
```
