### ISSUE TITLE
Cannot install from HACS on latest version of Home Assistant / HassOS

### ISSUE THREAD

**Issue by GraysonCAdams** [custom-components/pyscript#739]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pyscript/__init__.py", line 375, in async_setup_entry
    await watchdog_start(hass, pyscript_folder, reload_scripts_handler)
  File "/config/custom_components/pyscript/__init__.py", line 150, in watchdog_start
    class WatchDogHandler(FileSystemEventHandler):
    ...<46 lines>...
            self.process(event)
  File "/config/custom_components/pyscript/__init__.py", line 154, in WatchDogHandler
    self, watchdog_q: asyncio.Queue, observer: watchdog.observers.ObserverType, path: str
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'watchdog.observers' has no attribute 'ObserverType'
```

Looks like an import issue with Watchdog?  @craigbarratt Have you seen this before?

**Comment by robin-thoni** [comment]
Having this issue as well on `2025.7.3`. Was working well on `2025.7.1` or `2025.7.2` (Not sure from which one I just upgraded)

**Comment by robin-thoni** [comment]
The latest HA release seems to have downgraded from `watchdog==6.0.0` to `watchdog==1.0.1`:

<img width="708" height="549" alt="Image" src="https://github.com/user-attachments/assets/23c5d683-fffc-4f4e-a0fa-1bd99e31c463" />

https://github.com/gorakhargosh/watchdog/blob/v1.0.1/src/watchdog/observers/__init__.py:

<img width="758" height="634" alt="Image" src="https://github.com/user-attachments/assets/59c37bbd-2db3-46fe-bd46-b1a88faba7c2" />

Even though the `requirements_all.txt` file has not changed: https://github.com/home-assistant/core/blob/2025.7.3/requirements_all.txt#L3078

**Comment by robin-thoni** [comment]
Also confirmed by `pip freeze`:

<img width="775" height="86" alt="Image" src="https://github.com/user-attachments/assets/dd0ffa3d-4f9b-4f87-b1df-5317b16f7e09" />

That's an HA side issue. Not related to `pyscript`.

**Comment by robin-thoni** [comment]
Just opened an issue on the HA core side: https://github.com/home-assistant/core/issues/149513

**Comment by robin-thoni** [comment]
@GraysonCAdams Are you using the [SpotifyPlus integration](https://github.com/thlucas1/homeassistantcomponent_spotifyplus), by any chance?
Try disabling it restart HA. The problem comes from [this dependency](https://github.com/thlucas1/homeassistantcomponent_spotifyplus/blob/master/custom_components/spotifyplus/manifest.json#L19).

**Comment by robin-thoni** [comment]
Issue on `SpotifyPlus` side: https://github.com/thlucas1/homeassistantcomponent_spotifyplus/issues/142

**Comment by robin-thoni** [comment]
Thanks! Hopefully, @GraysonCAdams was affected by the same cause. For me, it was just a coincidence that I updated both HA and `SpotifyPlus` at the same time, tricking me into thinking it was due to HA `2025.7.x` update :)

**Comment by craigbarratt** [comment]
Thanks for getting to the bottom of the issue!
