### ISSUE TITLE
Service call fails 

### ISSUE THREAD

**Issue by stigvi** [custom-components/pyscript#179]
I upgraded to core version 2021.3.0 this evening and are getting errors shown below. It was working in 2021.2.3

`2021-03-03 22:15:48 ERROR (MainThread) [custom_components.pyscript.scripts.diverse.presence.activity] Exception in <scripts.diverse.presence.activity> line 45:
        timer.activity.start(duration = "02:00:00")
        ^
AttributeError: 'StateVal' object has no attribute 'start'`

`2021-03-03 22:22:19 ERROR (MainThread) [custom_components.pyscript.scripts.alarm.arm.armhome] Exception in <scripts.alarm.arm.armhome> line 6:
            alarm_control_panel.hjemmealarm.alarm_arm_home(code = "1234")
            ^
AttributeError: 'StateVal' object has no attribute 'alarm_arm_home'`

**Comment by craigbarratt** [comment]
2021.3.0 changed the way service's with entities works.  This should be fixed in master.  Please run master to confirm.

**Comment by stigvi** [comment]
Yes, I saw that in https://github.com/custom-components/pyscript/issues/173#issue-817665466 after I have posted. I have changed to master and can confirm that timer.start works now.

**Comment by craigbarratt** [comment]
Thanks for confirming.  Released 1.3.1 with this fix (and a couple of others).
