### ISSUE TITLE
pyscript template functions not working

### ISSUE THREAD

**Issue by BAPMU** [custom-components/pyscript#786]
after update to 2025.12.0 template functions doesn't work.

What version of Home Assistant Core has the issue?
2025.12.0

What was the last working version of Home Assistant Core?
last core before

What type of installation are you running?
Home Assistant OS

**pyscript function**
import homeassistant.helpers.template as template
def get_home_mainlabel(entity):
     label=template.labels(hass,entity)

**log**
2025-12-09 12:34:33.324 ERROR (MainThread) [custom_components.pyscript.file.lodge_cal_mgmt.get_booking] Exception in <file.lodge_cal_mgmt.get_booking> line 8:
        label=template.labels(hass,entity)
              ^
AttributeError: module 'homeassistant.helpers.template' has no attribute 'labels'

**Comment by ALERTua** [comment]
similar to https://github.com/custom-components/pyscript/issues/783
you are importing the homeassistant code, pyscript has nothing to do with it.
